---
title: "Research"
---
  
## Under Review
* Mask Wars: Sourcing a Critical Medical Product from China in Times of COVID-19 (with [Andreas Fuchs](http://www.andreas-fuchs.net/), [Lennart C. Kaplan](https://sites.google.com/view/lennart-kaplan/home), [Krisztina Kis-Katos](https://uni-goettingen.de/de/krisztina+kis-katos/545784.html), [Felix Turbanisch](https://www.uni-goettingen.de/en/614391.html) and [Feicheng Wang](https://www.uni-goettingen.de/en/570296.html)) \
Revision requested at the *Journal of International Economics* \
Working Paper: [Groningen](https://www.rug.nl/ggdc/html_publications/memorandum/gd194.pdf); \ 
Older Versions: [COVID Economics](https://cepr.org/file/9477/download?token=nfOJwrh_), [AidData](https://www.aiddata.org/publications/mask-wars-chinas-exports-of-medical-goods-in-times-of-covid-19); Media: [VoxEU](https://voxeu.org/article/china-s-mask-diplomacy), [Washington Post (Monkey Cage)](https://www.washingtonpost.com/politics/2021/01/29/china-sent-masks-gloves-gowns-many-us-states-heres-who-benefited/), [Kiel Policy Brief (in German)](https://www.ifw-kiel.de/de/publikationen/kiel-policy-briefs/2020/chinas-maskendiplomatie-die-rolle-politischer-und-wirtschaftlicher-beziehungen-bei-der-beschaffung-medizinischer-gueter-in-der-corona-krise-0/) 

## Working Papers
* Tracking Chinese Aid through China Customs: Darlings and Orphans after the COVID-19 Outbreak (with [Andreas Fuchs](http://www.andreas-fuchs.net/), [Lennart C. Kaplan](https://sites.google.com/view/lennart-kaplan/home), [Krisztina Kis-Katos](https://uni-goettingen.de/de/krisztina+kis-katos/545784.html), [Felix Turbanisch](https://www.uni-goettingen.de/en/614391.html) and [Feicheng Wang](https://www.uni-goettingen.de/en/570296.html)) \
Working Paper: [Kiel Working Paper](https://www.econstor.eu/handle/10419/264395); Data: [Chinese Aid Exports Database](http://china-aid-exports.uni-goettingen.de/); Media: [Bloomberg](https://www.bloomberg.com/news/articles/2022-11-15/china-s-aid-exports-hit-1-3-billion-last-year-on-vaccine-gifts),  [PEGNet Policy Brief](https://www.pegnet.ifw-kiel.de/policy-briefs/chinas-aid-exports-to-africa-and-the-covid-19-pandemic-how-much-where-what-16921/)

## Work in Progress

* Income and Migration: Evidence from a Century of Random Cash Transfers (with [Erik Haustein](https://erikhaustein.com/))

* Real Iceberg Transport Costs: The Distance Effect of the North Atlantic Iceberg Drift on Trade
(with [Christian Düben](https://www.christian-dueben.com/) and [Jonas F. Rudsinske](https://www.uni-goettingen.de/en/595283.html))

* Is Davos More Than a Boondoggle? (with [Andreas Fuchs](http://www.andreas-fuchs.net/) and [Andrew K. Rose](http://faculty.haas.berkeley.edu/arose/))

<!-- < cta cta_text="Working Paper" cta_link="https://www.aiddata.org/publications/mask-wars-chinas-exports-of-medical-goods-in-times-of-covid-19" > {{< cta cta_text="Working Paper" cta_link="https://www.aiddata.org/publications/mask-wars-chinas-exports-of-medical-goods-in-times-of-covid-19" >}}  -->

<!-- <cta cta_text=button name="button" onclick="http://www.google.com">Click me</button> <button name="button" onclick="http://www.google.com">Click me</button> -->

<!-- [Click me](http://www.google.com){: .btn} -->
<!-- <button name="button">Click me</button> -->
